name: ETL Games (API + Scraping)

on:
  workflow_dispatch: {}
  schedule:
    # 07:00 heure de Paris (05:00 UTC)
    - cron: "0 5 * * *"

jobs:
  run-etl:
    runs-on: self-hosted
    defaults:
      run:
        shell: pwsh   # 👉 force PowerShell sur Windows

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build .env from secrets (Windows PowerShell)
        run: |
          @"
          RAWG_API_KEY=${{ secrets.RAWG_API_KEY }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_TABLE=${{ secrets.DB_TABLE }}
          LOG_LEVEL=INFO
          HTTP_TIMEOUT=20
          HTTP_RETRIES=3
          SCRAPE_ENABLED=${{ secrets.SCRAPE_ENABLED }}
          SCRAPE_CONFIG=scrape_sources.json
          "@ | Set-Content -NoNewline .env

      - name: Write scrape_sources.json if provided
        run: |
          if ("${{ secrets.SCRAPE_CONFIG_JSON }}" -ne "") {
            "${{ secrets.SCRAPE_CONFIG_JSON }}" | Set-Content -NoNewline scrape_sources.json
            Write-Host "scrape_sources.json created from secret."
          } else {
            Write-Host "No SCRAPE_CONFIG_JSON secret; skipping."
          }

      - name: Run ETL (50 derniers jeux + update)
        run: python etl_games.py --limit 50

      - name: Upload log (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: etl-logs
          path: etl_games.log
          if-no-files-found: ignore
