name: ETL Games (API + Scraping)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 5 * * *"   # 07:00 Paris

jobs:
  run-etl:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ Multiple approaches to ensure script execution works
      - name: Relax PowerShell execution policy
        run: |
          # Try multiple scopes to ensure policy is set
          try {
            Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
            Write-Host "✅ Process scope policy set to Bypass"
          } catch {
            Write-Warning "Failed to set Process scope: $_"
          }
          
          try {
            Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned -Force
            Write-Host "✅ CurrentUser scope policy set to RemoteSigned"
          } catch {
            Write-Warning "Failed to set CurrentUser scope: $_"
          }
          
          # Verify current policy
          Write-Host "Current execution policies:"
          Get-ExecutionPolicy -List

      - name: Show PowerShell version
        run: $PSVersionTable

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build .env from secrets
        run: |
          @"
          RAWG_API_KEY=${{ secrets.RAWG_API_KEY }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_TABLE=${{ secrets.DB_TABLE }}
          LOG_LEVEL=INFO
          HTTP_TIMEOUT=20
          HTTP_RETRIES=3
          SCRAPE_ENABLED=${{ secrets.SCRAPE_ENABLED }}
          SCRAPE_CONFIG=scrape_sources.json
          "@ | Set-Content -NoNewline .env -Encoding UTF8

      - name: Write scrape_sources.json if provided
        run: |
          if ("${{ secrets.SCRAPE_CONFIG_JSON }}" -ne "") {
            "${{ secrets.SCRAPE_CONFIG_JSON }}" | Set-Content -NoNewline scrape_sources.json -Encoding UTF8
            Write-Host "scrape_sources.json created from secret."
          } else {
            Write-Host "No SCRAPE_CONFIG_JSON secret; skipping."
          }

      - name: Run ETL (50 derniers jeux + update)
        run: |
          # Ensure we can execute the Python script
          $env:PYTHONUNBUFFERED = "1"
          python etl_games.py --limit 50

      - name: Upload log (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: etl-logs
          path: etl_games.log
          if-no-files-found: ignore
