- name: Relax PowerShell execution policy
  shell: pwsh
  run: |
    Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
    Write-Host "✅ Execution policy set to Bypass for current process"
    Get-ExecutionPolicy -List

      - name: Show PowerShell version
        shell: pwsh
        run: $PSVersionTable

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Python version
        shell: cmd
        run: python --version

      - name: Install dependencies
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build .env from secrets
        shell: pwsh
        run: |
          @"
          RAWG_API_KEY=${{ secrets.RAWG_API_KEY }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_TABLE=${{ secrets.DB_TABLE }}
          LOG_LEVEL=INFO
          HTTP_TIMEOUT=20
          HTTP_RETRIES=3
          SCRAPE_ENABLED=${{ secrets.SCRAPE_ENABLED }}
          SCRAPE_CONFIG=scrape_sources.json
          "@ | Set-Content -NoNewline .env -Encoding UTF8

      - name: Write scrape_sources.json if provided
        shell: pwsh
        run: |
          if ("${{ secrets.SCRAPE_CONFIG_JSON }}" -ne "") {
            "${{ secrets.SCRAPE_CONFIG_JSON }}" | Set-Content -NoNewline scrape_sources.json -Encoding UTF8
            Write-Host "scrape_sources.json created from secret."
          } else {
            Write-Host "No SCRAPE_CONFIG_JSON secret; skipping."
          }

      - name: Run ETL (50 derniers jeux + update)
        shell: cmd
        run: python etl_games.py --limit 50
